// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// global_topk
List global_topk(IntegerVector tp, IntegerVector ti, IntegerVector qp, IntegerVector qi, NumericVector rs_test, NumericVector rs_train, LogicalVector cp4_ok, int n_train, int k);
RcppExport SEXP _skillviz_global_topk(SEXP tpSEXP, SEXP tiSEXP, SEXP qpSEXP, SEXP qiSEXP, SEXP rs_testSEXP, SEXP rs_trainSEXP, SEXP cp4_okSEXP, SEXP n_trainSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type tp(tpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ti(tiSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type qp(qpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type qi(qiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rs_test(rs_testSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rs_train(rs_trainSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type cp4_ok(cp4_okSEXP);
    Rcpp::traits::input_parameter< int >::type n_train(n_trainSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(global_topk(tp, ti, qp, qi, rs_test, rs_train, cp4_ok, n_train, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_skillviz_global_topk", (DL_FUNC) &_skillviz_global_topk, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_skillviz(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
