# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

global_topk <- function(tp, ti, qp, qi, rs_test, rs_train, cp4_ok, n_train, k) {
    .Call(`_skillviz_global_topk`, tp, ti, qp, qi, rs_test, rs_train, cp4_ok, n_train, k)
}

